language: python
python:
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
install:
    - "pip install -r requirements.txt"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py syncdb --noinput
  - sqlite3 sample_db.sqlite3 .schema > schema
  - sqlite3 sample_db.sqlite3 .dump > dump
  - grep -v -f schema dump > data
  - psql -d travis_ci_test < data
# command to run tests
script:
  - python manage.py test --settings=Practice_Referral.test_settings --noinput

notifications:
  email: false
